# Generated by Django 5.2.3 on 2025-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
