# Generated by Django 5.2.3 on 2025-07-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_unpublish_product", "может отменять публикацию продукта"),
                    ("can_delete_product", "может удалять публикацию продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
